### ISSUE TITLE
Allow custodian pay in the native token, not just EOS

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdac-contracts#36]

**Comment by str** [comment]
While the issue about using native token instead of EOS to pay the custodians is being solved,  is it possible to disable the paying feature at all?

**Comment by michaeljyeates** [comment]
I think you can set the max requested pay to 0.0000 EOS

**Comment by dallasjohnson** [comment]
There is not explicit setting to disable payment but the payment actions will only be scheduled as deferred transactions to custodians if the payment amount is greater than 0. So to disable the payments Michael's suggestion would be the easiest option and would still be efficient on CPU usage since it would not try to post deferred payment actions for 0 amounts. If there is enough demand for for this feature then we could implement it as another setting but I would prefer to hold off on adding extra settings until we really need them when there is another way to achieve the same outcome.

**Comment by dallasjohnson** [comment]
Otherwise this issue has now been implemented and allows for any `eosio.token` compatible contract to be the payment contract via the use of `extended_asset` for the setting of `requested_pay_max` in the `daccustodian` contract.

**Comment by str** [comment]
I think the "disable payments" new feature should be in another issue, to keep track of how many people are interested. Setting the max request to 0.0000 makes sense, I think with that, the only changes needed are in the client/gui side where if the max request is set to zero, then it should not show the payments field.

@dallasjohnson let me know if that makes sense to you too and if so, who should create the ticket and in which repo. 

>  allows for any eosio.token compatible contract to be the payment contract via the use of extended_asset

Thank you for that.

**Comment by dallasjohnson** [comment]
@str I think that makes sense. Then the the UI client could be configured to hide the custodian payments  features if the `requestedMaxPay` == 0 for a given DAC. The best place for this issue would be in the https://github.com/eosdac/eosdac-client repo. I'm more than happy for you to create the issue for that. And also a separate issue to track the demand for a "disable payments" feature at a contract level in this repo as you suggested.

**Comment by str** [comment]
@dallasjohnson  done: https://github.com/eosdac/eosdac-client/issues/88
